jenkins updated

diff --git a/{ b/{
--- a/{
+++ b/{
@@ -165,4 +165,112 @@ Script started on 2025-03-19 08:35:39+00:00 [TERM="xterm-256color" TTY="/dev/pts
             echo "Build or container execution failed."
         }
     }
-}ipeline
+}ipeline {
+    agent any
+    environment {
+        DOCKER_IMAGE = "mouleeshwaran28/docker-app:latest"  // Change this to your registry
+        CONTAINER_NAME = "docker-running-app"
+        REGISTRY_CREDENTIALS = "docker-hub-credentials"  // Jenkins credentials ID
+    }
+
+    stages {
+        stage('Checkout Code') {
+            steps {
+                withCredentials([usernamePassword(credentialsId: 'github-mouleesh', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_TOKEN')]) {
+                    git url: "https://$GIT_USER:$GIT_TOKEN@github.com/Mouleesh28/jenkins-docker-demo.git", branch: 'main'
+                }
+            }
+        }
+
+        stage('Build Docker Image') {
+            steps {
+                sh 'docker build -t $DOCKER_IMAGE .'
+            }
+        }
+
+        stage('Login to Docker Registry') {
+            steps {
+                withCredentials([usernamePassword(credentialsId: 'github-mouleesh', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
+                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
+                }
+            }
+        }
+
+        stage('Push to Container Registry') {
+            steps {
+                sh 'docker push $DOCKER_IMAGE'
+            }
+        }
+
+        stage('Stop & Remove Existing Container') {
+            steps {
+                script {
+                    sh '''
+                    if [ "$(docker ps -aq -f name=$CONTAINER_NAME)" ]; then
+                        docker stop $CONTAINER_NAME || true
+                        docker rm $CONTAINER_NAME || true
+                    fi
+                    '''
+                }
+            }
+        }
+
+        stage('Run Docker Container') {
+            steps {
+                sh 'docker run -d -p 5001:5000 --name $CONTAINER_NAME $DOCKER_IMAGE'
+            }
+        }
+    }
+
+    post {
+        success {
+            echo "Build, push, and container execution successful!"
+        }
+        failure {
+            echo "Build or container execution failed."
+        }
+    }
+}
+[?2004h]0;mouleesh@DESKTOP-PBBPDK2: ~/docker-python-app/Jenkins-Docker-Demo[01;32mmouleesh@DESKTOP-PBBPDK2[00m:[01;34m~/docker-python-app/Jenkins-Docker-Demo[00m$ git add. [K[K .[K[K[K[K[K[K[K[K[Kgit add .
+[?2004l[?2004h]0;mouleesh@DESKTOP-PBBPDK2: ~/docker-python-app/Jenkins-Docker-Demo[01;32mmouleesh@DESKTOP-PBBPDK2[00m:[01;34m~/docker-python-app/Jenkins-Docker-Demo[00m$ git sa[Kts[Kar[Ktus
+[?2004lOn branch main
+Your branch is ahead of 'origin/main' by 1 commit.
+  (use "git push" to publish your local commits)
+
+Changes to be committed:
+  (use "git restore --staged <file>..." to unstage)
+	[32mnew file:   jenkins[m
+	[32mnew file:   {[m
+
+[?2004h]0;mouleesh@DESKTOP-PBBPDK2: ~/docker-python-app/Jenkins-Docker-Demo[01;32mmouleesh@DESKTOP-PBBPDK2[00m:[01;34m~/docker-python-app/Jenkins-Docker-Demo[00m$ git commit -m ""j"e"n"k"i"n"s" "c"o"m"m"i"t"e"d"
+[?2004l[main dfddf11] jenkins commited
+ 2 files changed, 364 insertions(+)
+ create mode 100644 jenkins
+ create mode 100644 {
+[?2004h]0;mouleesh@DESKTOP-PBBPDK2: ~/docker-python-app/Jenkins-Docker-Demo[01;32mmouleesh@DESKTOP-PBBPDK2[00m:[01;34m~/docker-python-app/Jenkins-Docker-Demo[00m$ git push
+[?2004lUsername for 'https://github.com': Mouleesh28
+Password for 'https://Mouleesh28@github.com': 
+remote: Support for password authentication was removed on August 13, 2021.
+remote: Please see https://docs.github.com/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
+fatal: Authentication failed for 'https://github.com/Mouleesh28/Jenkins-Docker-Demo.git/'
+[?2004h]0;mouleesh@DESKTOP-PBBPDK2: ~/docker-python-app/Jenkins-Docker-Demo[01;32mmouleesh@DESKTOP-PBBPDK2[00m:[01;34m~/docker-python-app/Jenkins-Docker-Demo[00m$ git pushcommit -m "jenkins commited"status[K[1Padd .cat jenkins[1@nano[C[C[C[C[C[C[C[Csudo docker run -itd -p 5000:5000 testdocker ps[Ksudo usermod -aG docker $USERdocker run -itd -p 5000:5000 test[5P[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[13P itd -p itd -p 5000:5000 test[5@sudo [C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[9Pusermod -aG docker $USERdocker ps[Ksudo docker run -itd -p 5000:5000 testnano jenkins[K[1Pcat[C[C[C[C[C[C[C[C[2Pgit add .statuscommit -m "jenkins commited"push[K[K[7m git push https://Mouleesh28:ghp_iTHxgpgerrGd1JpG1MDRrssr7q9S8G1WvJ[27m[7mj[27m[7m [27m
+[7mj@github.com/Mouleesh28/Jenkins-Docker-Demo.git[27m[A[A]0;mouleesh@DESKTOP-PBBPDK2: ~/docker-python-app/Jenkins-Docker-Demo[01;32mmouleesh@DESKTOP-PBBPDK2[00m:[01;34m~/docker-python-app/Jenkins-Docker-Demo[00m$  git push https://Mouleesh28:ghp_iTHxgpgerrGd1JpG1MDRrssr7q9S8G1WvJj
+j@github.com/Mouleesh28/Jenkins-Docker-Demo.git
+[?2004lfatal: unable to access 'https://Mouleesh28:ghp_iTHxgpgerrGd1JpG1MDRrssr7q9S8G1WvJj/': URL rejected: Port number was not a decimal number between 0 and 65535
+bash: j@github.com/Mouleesh28/Jenkins-Docker-Demo.git: No such file or directory
+[?2004h]0;mouleesh@DESKTOP-PBBPDK2: ~/docker-python-app/Jenkins-Docker-Demo[01;32mmouleesh@DESKTOP-PBBPDK2[00m:[01;34m~/docker-python-app/Jenkins-Docker-Demo[00m$ [7mgit push https://Mouleesh28:ghp_iTHxgpgerrGd1JpG1MDRrssr7q9S8G1WvJj[27m 
+[7mj@github.com/Mouleesh28/Jenkins-Docker-Demo.git[27m[A[A]0;mouleesh@DESKTOP-PBBPDK2: ~/docker-python-app/Jenkins-Docker-Demo[01;32mmouleesh@DESKTOP-PBBPDK2[00m:[01;34m~/docker-python-app/Jenkins-Docker-Demo[00m$ git push https://Mouleesh28:ghp_iTHxgpgerrGd1JpG1MDRrssr7q9S8G1WvJj 
+j@github.com/Mouleesh28/Jenkins-Docker-Demo.git
+[?2004lfatal: unable to access 'https://Mouleesh28:ghp_iTHxgpgerrGd1JpG1MDRrssr7q9S8G1WvJj/': URL rejected: Port number was not a decimal number between 0 and 65535
+bash: j@github.com/Mouleesh28/Jenkins-Docker-Demo.git: No such file or directory
+[?2004h]0;mouleesh@DESKTOP-PBBPDK2: ~/docker-python-app/Jenkins-Docker-Demo[01;32mmouleesh@DESKTOP-PBBPDK2[00m:[01;34m~/docker-python-app/Jenkins-Docker-Demo[00m$ j@github.com/Mouleesh28/Jenkins-Docker-Demo.gitgit push https://Mouleesh28:ghp_iTHxgpgerrGd1JpG1MDRrssr7q9S8G1WvJj [A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[20Pj@github.com/Mouleesh28/Jenkins-Docker-Demo.git
+[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cgit push https://Mouleesh28:ghp_iTHxgpgerrGd1JpG1MDRrssr7q9S8G1WvJj [A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[20Pj@github.com/Mouleesh28/Jenkins-Docker-Demo.git
+[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[K[7m git push https://Mouleesh28:ghp_iTHxgpgerrGd1JpG1MDRrssr7q9S8G1WvJ[27m[7mj[27m[7m [27m
+[7mj@github.com/Mouleesh28/Jenkins-Docker-Demo.git[27m[A[A]0;mouleesh@DESKTOP-PBBPDK2: ~/docker-python-app/Jenkins-Docker-Demo[01;32mmouleesh@DESKTOP-PBBPDK2[00m:[01;34m~/docker-python-app/Jenkins-Docker-Demo[00m$  git push https://Mouleesh28:ghp_iTHxgpgerrGd1JpG1MDRrssr7q9S8G1WvJj
+j@github.com/Mouleesh28/Jenkins-Docker-Demo.git[7m git push https://Mouleesh28:ghp_iTHxgpgerrGd1JpG1MDRrssr7q9S8G1WvJj[27m
+[7mj@github.com/Mouleesh28/Jenkins-Docker-Demo.git[27m[A git push https://Mouleesh28:ghp_iTHxgpgerrGd1JpG1MDRrssr7q9S8G1WvJj
+[1Pj@github.com/Mouleesh28/Jenkins-Docker-Demo.gi[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[A[C[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[K
+[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[7m git push https://Mouleesh28:ghp_iTHxgpgerrGd1JpG1MDRrssr7q9S8G1WvJ[27m[7mj[27m[7m [27m
+[7mj@github.com/Mouleesh28/Jenkins-Docker-Demo.git[27m[A[A]0;mouleesh@DESKTOP-PBBPDK2: ~/docker-python-app/Jenkins-Docker-Demo[01;32mmouleesh@DESKTOP-PBBPDK2[00m:[01;34m~/docker-python-app/Jenkins-Docker-Demo[00m$  git push https://Mouleesh28:ghp_iTHxgpgerrGd1JpG1MDRrssr7q9S8G1WvJj
+[1Pj@github.com/Mouleesh28/Jenkins-Docker-Demo.gi[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[A[C[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[K
+[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C
